
---
- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - ~/.dotfiles/vault.yml
  roles:
    - homebrew
    - macos
    - shell 
    - dotfiles
    - app_cleanup
    - keyboard
    - yabai
