---
- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - vars/secrets.yml
  roles:
    - homebrew
    - macos
    - shell
    - ssh
    - yabai
    - sketchybar
    - keyboard
    - alacritty
    - neovim
    - vscode
