
---
# Configure bash as default shell

- name: Ensure bash is available in /etc/shells
  shell: |
    grep -qx "/bin/bash" /etc/shells || echo "/bin/bash" | sudo tee -a /etc/shells

- name: Set bash as the default login shell
  shell: chsh -s /bin/bash
  when: ansible_env.SHELL != "/bin/bash"


